luffing_cranes:
  - parameters:
      x: 0.0
      y: 0.0
      h: 40.0
      d: 0.0
      jib_length: 50.0
  - parameters:
      x: 100.0
      y: 100.0
      h: 40.0
      d: 0.0
      jib_length: 50.0
tower_cranes:
  - parameters:
      x: 80.0
      y: 0.0
      h: 40.0
      jib_length: 50.0
